/*CREATE VIEW [dbo].[vwCEOsWithOffice365OrAzure]
	AS 
	SELECT * FROM TWITTERPROFILESWITHCEO TPWCEO
INNER JOIN TWITTERUSERSTATUS TUS ON TPWCEO.TWITTERACCOUNTSID = TUS.TWITTERACCOUNTSID
WHERE TPWCEO.PROFILEDESCRIPTION LIKE '%AZURE%' OR TUS.STATUSTEXT LIKE '%AZURE%'
OR TPWCEO.PROFILEDESCRIPTION LIKE '%OFFICE 365%' OR TUS.STATUSTEXT LIKE '%OFFICE 365%'
OR TPWCEO.PROFILEDESCRIPTION LIKE '%#OFFICE365%' OR TUS.STATUSTEXT LIKE '%#OFFICE365%'

*/