CREATE VIEW [dbo].[vwDomainCheckTodayStatus]
	AS
SELECT CONVERT(DATE,DL.CHECKEDDATETIME) AS [DATE], DI.DOMAIN, DI.WEBSITE,
DL.ResponseMessage, ISNULL(DL.RESPONSECODE,'NULL RESPONSE') AS RESPONSECODE, COUNT(DL.RESPONSEMESSAGE) AS TIMESMESSAGERECEIVED
FROM DOMAININFO DI
INNER JOIN DOMAINLOOKUP DL ON DL.DOMAINID = DI.DOMAININFOID
--WHERE DL.RESPONSECODE IS NULL OR DL.RESPONSECODE <> 'OK'
WHERE CONVERT(DATE,DL.CHECKEDDATETIME) = CONVERT(DATE,GETUTCDATE())
GROUP BY CONVERT(DATE,DL.CHECKEDDATETIME), DI.DOMAIN, DI.WEBSITE, DL.RESPONSEMESSAGE, DL.RESPONSECODE
