CREATE VIEW [dbo].[vwDomainCheckYearlyStatus]
	AS
	SELECT DATEPART(MONTH,DL.CHECKEDDATETIME) AS [MONTH], DATEPART(YEAR,DL.CHECKEDDATETIME) AS [YEAR], DI.DOMAIN, DI.WEBSITE,
DL.ResponseMessage, ISNULL(DL.RESPONSECODE,'NULL RESPONSE') AS RESPONSECODE, COUNT(DL.RESPONSEMESSAGE) AS TIMESMESSAGERECEIVED
FROM DOMAININFO DI
INNER JOIN DOMAINLOOKUP DL ON DL.DOMAINID = DI.DOMAININFOID
--WHERE DL.RESPONSECODE IS NULL OR DL.RESPONSECODE <> 'OK'
GROUP BY DATEPART(MONTH,DL.CHECKEDDATETIME), DATEPART(YEAR,DL.CHECKEDDATETIME), DI.DOMAIN, DI.WEBSITE, DL.RESPONSEMESSAGE, DL.RESPONSECODE
