CREATE VIEW [dbo].[vwNetworkFollowersPerLocation]
	AS 
	SELECT TOP 10 TA.[Location], COUNT(*) FOLLOWERSINLOCATION FROM FOLLOWERS TF WITH (NOLOCK)
INNER JOIN TWITTERACCOUNT TA WITH (NOLOCK) ON TA.USERNAME = TF.USERFOLLOWING
--WHERE TF.USERFOLLOWED = ''
WHERE TA.LOCATION IS NOT NULL AND TA.LOCATION <> ''
GROUP BY TA.LOCATION
ORDER BY COUNT(*) DESC
