// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace CustomerFinderCognitiveServices.Models
{
    public partial class KeyPhraseBatchResultItemV2
    {
        private string _id;
        
        /// <summary>
        /// Optional. Unique document identifier.
        /// </summary>
        public string ID
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private IList<string> _keyPhrases;
        
        /// <summary>
        /// Optional. A list of representative words or phrases. The number of
        /// key phrases returned is proportional to the number of words in the
        /// input document.
        /// </summary>
        public IList<string> KeyPhrases
        {
            get { return this._keyPhrases; }
            set { this._keyPhrases = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the KeyPhraseBatchResultItemV2 class.
        /// </summary>
        public KeyPhraseBatchResultItemV2()
        {
            this.KeyPhrases = new LazyList<string>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken idValue = inputObject["id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.ID = ((string)idValue);
                }
                JToken keyPhrasesSequence = ((JToken)inputObject["keyPhrases"]);
                if (keyPhrasesSequence != null && keyPhrasesSequence.Type != JTokenType.Null)
                {
                    foreach (JToken keyPhrasesValue in ((JArray)keyPhrasesSequence))
                    {
                        this.KeyPhrases.Add(((string)keyPhrasesValue));
                    }
                }
            }
        }
    }
}
