// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using CustomerFinderCognitiveServices.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace CustomerFinderCognitiveServices.Models
{
    public partial class LanguageBatchResultV2
    {
        private IList<LanguageBatchResultItemV2> _documents;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<LanguageBatchResultItemV2> Documents
        {
            get { return this._documents; }
            set { this._documents = value; }
        }
        
        private IList<ErrorRecordV2> _errors;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<ErrorRecordV2> Errors
        {
            get { return this._errors; }
            set { this._errors = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the LanguageBatchResultV2 class.
        /// </summary>
        public LanguageBatchResultV2()
        {
            this.Documents = new LazyList<LanguageBatchResultItemV2>();
            this.Errors = new LazyList<ErrorRecordV2>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken documentsSequence = ((JToken)inputObject["documents"]);
                if (documentsSequence != null && documentsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken documentsValue in ((JArray)documentsSequence))
                    {
                        LanguageBatchResultItemV2 languageBatchResultItemV2 = new LanguageBatchResultItemV2();
                        languageBatchResultItemV2.DeserializeJson(documentsValue);
                        this.Documents.Add(languageBatchResultItemV2);
                    }
                }
                JToken errorsSequence = ((JToken)inputObject["errors"]);
                if (errorsSequence != null && errorsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken errorsValue in ((JArray)errorsSequence))
                    {
                        ErrorRecordV2 errorRecordV2 = new ErrorRecordV2();
                        errorRecordV2.DeserializeJson(errorsValue);
                        this.Errors.Add(errorRecordV2);
                    }
                }
            }
        }
    }
}
