// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using CustomerFinderCognitiveServices.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace CustomerFinderCognitiveServices.Models
{
    public partial class OperationProcessingResult
    {
        private IList<ErrorRecordV2> _errors;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<ErrorRecordV2> Errors
        {
            get { return this._errors; }
            set { this._errors = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the OperationProcessingResult class.
        /// </summary>
        public OperationProcessingResult()
        {
            this.Errors = new LazyList<ErrorRecordV2>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken errorsSequence = ((JToken)inputObject["errors"]);
                if (errorsSequence != null && errorsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken errorsValue in ((JArray)errorsSequence))
                    {
                        ErrorRecordV2 errorRecordV2 = new ErrorRecordV2();
                        errorRecordV2.DeserializeJson(errorsValue);
                        this.Errors.Add(errorRecordV2);
                    }
                }
            }
        }
    }
}
