// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace CustomerFinderCognitiveServices.Models
{
    public partial class TopicInfoRecordV2
    {
        private string _id;
        
        /// <summary>
        /// Optional. A unique identifier for each topic.
        /// </summary>
        public string ID
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _keyPhrase;
        
        /// <summary>
        /// Optional. A summarizing word or phrase for the topic.
        /// </summary>
        public string KeyPhrase
        {
            get { return this._keyPhrase; }
            set { this._keyPhrase = value; }
        }
        
        private double? _score;
        
        /// <summary>
        /// Optional. Count of documents assigned to topic.
        /// </summary>
        public double? Score
        {
            get { return this._score; }
            set { this._score = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the TopicInfoRecordV2 class.
        /// </summary>
        public TopicInfoRecordV2()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken idValue = inputObject["id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.ID = ((string)idValue);
                }
                JToken keyPhraseValue = inputObject["keyPhrase"];
                if (keyPhraseValue != null && keyPhraseValue.Type != JTokenType.Null)
                {
                    this.KeyPhrase = ((string)keyPhraseValue);
                }
                JToken scoreValue = inputObject["score"];
                if (scoreValue != null && scoreValue.Type != JTokenType.Null)
                {
                    this.Score = ((double)scoreValue);
                }
            }
        }
    }
}
