// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace CustomerFinderCognitiveServices.Models
{
    public partial class TopicAssignmentRecordV2
    {
        private double? _distance;
        
        /// <summary>
        /// Optional. Document-to-topic affiliation score between 0 and 1. The
        /// lower a distance score the stronger the topic affiliation is.
        /// </summary>
        public double? Distance
        {
            get { return this._distance; }
            set { this._distance = value; }
        }
        
        private string _documentId;
        
        /// <summary>
        /// Optional. Identifier for the document. Equates to the ID included
        /// in the input.
        /// </summary>
        public string DocumentId
        {
            get { return this._documentId; }
            set { this._documentId = value; }
        }
        
        private string _topicId;
        
        /// <summary>
        /// Optional. The topic ID which the document has been assigned to.
        /// </summary>
        public string TopicId
        {
            get { return this._topicId; }
            set { this._topicId = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the TopicAssignmentRecordV2 class.
        /// </summary>
        public TopicAssignmentRecordV2()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken distanceValue = inputObject["distance"];
                if (distanceValue != null && distanceValue.Type != JTokenType.Null)
                {
                    this.Distance = ((double)distanceValue);
                }
                JToken documentIdValue = inputObject["documentId"];
                if (documentIdValue != null && documentIdValue.Type != JTokenType.Null)
                {
                    this.DocumentId = ((string)documentIdValue);
                }
                JToken topicIdValue = inputObject["topicId"];
                if (topicIdValue != null && topicIdValue.Type != JTokenType.Null)
                {
                    this.TopicId = ((string)topicIdValue);
                }
            }
        }
    }
}
