// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using CustomerFinderCognitiveServices.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace CustomerFinderCognitiveServices.Models
{
    public partial class TopicDetectionResultV2 : OperationProcessingResult
    {
        private IList<TopicAssignmentRecordV2> _topicAssignments;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<TopicAssignmentRecordV2> TopicAssignments
        {
            get { return this._topicAssignments; }
            set { this._topicAssignments = value; }
        }
        
        private IList<TopicInfoRecordV2> _topics;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<TopicInfoRecordV2> Topics
        {
            get { return this._topics; }
            set { this._topics = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the TopicDetectionResultV2 class.
        /// </summary>
        public TopicDetectionResultV2()
        {
            this.TopicAssignments = new LazyList<TopicAssignmentRecordV2>();
            this.Topics = new LazyList<TopicInfoRecordV2>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public override void DeserializeJson(JToken inputObject)
        {
            base.DeserializeJson(inputObject);
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken topicAssignmentsSequence = ((JToken)inputObject["topicAssignments"]);
                if (topicAssignmentsSequence != null && topicAssignmentsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken topicAssignmentsValue in ((JArray)topicAssignmentsSequence))
                    {
                        TopicAssignmentRecordV2 topicAssignmentRecordV2 = new TopicAssignmentRecordV2();
                        topicAssignmentRecordV2.DeserializeJson(topicAssignmentsValue);
                        this.TopicAssignments.Add(topicAssignmentRecordV2);
                    }
                }
                JToken topicsSequence = ((JToken)inputObject["topics"]);
                if (topicsSequence != null && topicsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken topicsValue in ((JArray)topicsSequence))
                    {
                        TopicInfoRecordV2 topicInfoRecordV2 = new TopicInfoRecordV2();
                        topicInfoRecordV2.DeserializeJson(topicsValue);
                        this.Topics.Add(topicInfoRecordV2);
                    }
                }
            }
        }
    }
}
